# Generated by Django 2.1.5 on 2019-03-28 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lawsuit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crime_type', models.CharField(choices=[('民事', 0), ('刑事', 1)], max_length=16)),
            ],
        ),
    ]
