# Generated by Django 2.1.5 on 2019-03-28 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lawsuits', '0002_auto_20190328_1743'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lawsuit',
            name='crime_type',
            field=models.CharField(choices=[('民事', '民事'), ('刑事', '刑事')], max_length=16, verbose_name='案件类型'),
        ),
        migrations.AlterField(
            model_name='lawsuit',
            name='proc_type',
            field=models.CharField(choices=[('判决书', '判决书'), ('裁定书', '裁定书')], default=1, max_length=16, verbose_name='文书类型'),
        ),
        migrations.AlterField(
            model_name='lawsuit',
            name='procedure',
            field=models.CharField(choices=[('一审', '一审'), ('二审', '二审'), ('其他', '其他')], default=0, max_length=16, verbose_name='庭审程序'),
        ),
    ]
